@WebApi_HostAddress = https://localhost:44378

GET {{WebApi_HostAddress}}/
Accept: application/json

###

PATCH https://localhost:5224/api/v1/admin/quizzes/1
Content-Type: application/json-patch+json

[{
  "op": "add",
  "path": "/items/-",
  "value": {
    "question": "4*7",
    "correctAnswer": "28",
    "incorrectAnswers": ["27", "28", "29"]
  }
}]

###

PATCH https://localhost:7119/api/v1/admin/quizzes/1
Content-Type: application/json-patch+json

[
  {
    "op": "replace",
    "path": "title",
    "value": "Arytmetyka"
  }
]

###

PATCH https://localhost:7119/api/v1/admin/quizzes/1
Content-Type: application/json-patch+json

[
  {
    "op": "remove",
    "path": "/items/0"
  }
]

###

PATCH https://localhost:5224/api/v1/admin/quizzes/1
Content-Type: application/json-patch+json

[
  {
    "op": "asd",
    "path": "items/-",
    "value": 
  }
]

###

POST  https://localhost:7077/api/v1/quizzes/1/items/1/answer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoia2Fyb2wiLCJnZW5kZXIiOiJtYWxlIiwiZW1haWwiOiJrYXJvbEB3c2VpLmVkdS5wbCIsImV4cCI6MTY4MTMwODAwNCwianRpIjoiMWQ3NWZhYzUtZWVlMS00NWI1LTgwMjYtOGQ2MWIwMTUyNThhIiwiYXVkIjoid3NlaSIsImlzcyI6IndzZWkifQ.Ks6Lpep_t63Vy-1FFgr_4vroNO3p8JgOybghZ1qdMrI

{
  "userId": 1,
  "answer": "5"
}

